// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD_cBNElcGtx16SriacBPNoEE81rn0v9U',
    appId: '1:152119704745:web:b5aa01a590289ee4ccbdb8',
    messagingSenderId: '152119704745',
    projectId: 'planno-bdf6a',
    authDomain: 'planno-bdf6a.firebaseapp.com',
    databaseURL: 'https://planno-bdf6a-default-rtdb.firebaseio.com',
    storageBucket: 'planno-bdf6a.firebasestorage.app',
    measurementId: 'G-WTC5W9K47T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkhBlR_Rh_NlC7MD_MOghpULPmqwli3s',
    appId: '1:152119704745:android:7a340ae3d4ebfc07ccbdb8',
    messagingSenderId: '152119704745',
    projectId: 'planno-bdf6a',
    databaseURL: 'https://planno-bdf6a-default-rtdb.firebaseio.com',
    storageBucket: 'planno-bdf6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohLJKC0unmaGngtwoGavzYm-uZo7n8X0',
    appId: '1:152119704745:ios:075d3f6fdea3f2daccbdb8',
    messagingSenderId: '152119704745',
    projectId: 'planno-bdf6a',
    databaseURL: 'https://planno-bdf6a-default-rtdb.firebaseio.com',
    storageBucket: 'planno-bdf6a.firebasestorage.app',
    iosClientId: '152119704745-d1oe0ppg3p6s2p83epcae8com7ni7736.apps.googleusercontent.com',
    iosBundleId: 'com.example.planno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBohLJKC0unmaGngtwoGavzYm-uZo7n8X0',
    appId: '1:152119704745:ios:075d3f6fdea3f2daccbdb8',
    messagingSenderId: '152119704745',
    projectId: 'planno-bdf6a',
    databaseURL: 'https://planno-bdf6a-default-rtdb.firebaseio.com',
    storageBucket: 'planno-bdf6a.firebasestorage.app',
    iosClientId: '152119704745-d1oe0ppg3p6s2p83epcae8com7ni7736.apps.googleusercontent.com',
    iosBundleId: 'com.example.planno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD_cBNElcGtx16SriacBPNoEE81rn0v9U',
    appId: '1:152119704745:web:f34d015910dce344ccbdb8',
    messagingSenderId: '152119704745',
    projectId: 'planno-bdf6a',
    authDomain: 'planno-bdf6a.firebaseapp.com',
    databaseURL: 'https://planno-bdf6a-default-rtdb.firebaseio.com',
    storageBucket: 'planno-bdf6a.firebasestorage.app',
    measurementId: 'G-T2T2VPV85V',
  );
}
